[package]
name = "porthmos-vfs"
description = "The virtual filesystem contract every Porthmos protocol implements"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
testing = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["sync", "io-util", "fs", "time", "rt"] }

[dev-dependencies]
tokio.workspace = true
tempfile.workspace = true
porthmos-vfs = { path = ".", features = ["testing"] }
