[package]
name = "porthmos-tui"
description = "A dual-panel file manager for local files and SSH/SFTP connections"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "porthmos"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
porthmos-core.workspace = true
crossterm.workspace = true
futures-util.workspace = true
ratatui.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
unicode-width.workspace = true

[dev-dependencies]
tempfile.workspace = true
