[package]
name = "porthmos-sftp"
description = "SSH/SFTP protocol support for Porthmos"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
russh.workspace = true
russh-sftp.workspace = true
porthmos-ssh.workspace = true
porthmos-vfs.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
async-trait.workspace = true
